- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Get the version of bottom installed
  ansible.builtin.set_fact:
    bottom_version: "{{ ansible_facts.packages['bottom'][0]['version'] }}"
  when: '"bottom" in ansible_facts.packages'

- name: Get the latest version of bottom
  ansible.builtin.uri:
    url: https://api.github.com/repos/ClementTsang/bottom/releases/latest
    return_content: true
    method: GET
  register: bottom_latest_raw

- name: Extract the latest version of bottom
  ansible.builtin.set_fact:
    bottom_latest_version: "{{ bottom_latest_raw.json | community.general.json_query('tag_name') }}"

- name: Install (debian)
  ansible.builtin.include_tasks: debian.yml
  when:
    - ansible_os_family | lower == "debian"
    - bottom_version is not defined or (bottom_version is defined and bottom_version != bottom_latest_version)
