- name: Dotfiles provisionning
  hosts:
    - localhost
    - remotemachines
  vars:
    vscode_extensions:
      - redhat.ansible
      - redhat.vscode-yaml
      - akamud.vscode-theme-onedark
      - alexdima.copy-relative-path
      - golang.go
      - pkief.material-icon-theme
      - mhutchie.git-graph
      - jebbs.plantuml
      - hashicorp.terraform
  vars_prompt:
    - name: node_version
      prompt: Which version of node would you like to install ?
      default: "lts"
      private: false
  pre_tasks:
    - name: Run pre tasks
      ansible.builtin.include_tasks: pre/main.yml
  post_tasks:
    - name: Run post tasks
      ansible.builtin.include_tasks: post/main.yml
  roles:
    - bottom
    - docker
    - gcloud
    - git
    - go
    - k9s
    - kubectl
    - neovim
    - nerd_font
    - node
    - python
    - terraform
    - vscode
    - zsh
