---
- hosts: localhost
  vars:
    vscode_extensions:
      - redhat.ansible
      - akamud.vscode-theme-onedark
      - alexdima.copy-relative-path
      - golang.go
      - pkief.material-icon-theme
      - mhutchie.git-graph
      - jebbs.plantuml
      - hashicorp.terraform

  roles:
    - pre
    - system
    - git
    - zsh
    - neovim
    - k9s
    - vscode-server
    - vscode
    - podman
    - terraform
    - bottom
    