---
- hosts: localhost
  vars:
    vscode_extensions:
      - redhat.ansible
      - akamud.vscode-theme-onedark
      - alexdima.copy-relative-path
      - golang.go
      - pkief.material-icon-theme
      - mhutchie.git-graph
      - jebbs.plantuml
      - hashicorp.terraform

  pre_tasks:
    - include_tasks: pre/main.yml
  post_tasks:
    - include_tasks: post/main.yml

  roles:
    - zsh
    - bottom
    - git
    - go
    - k9s
    - neovim
    - docker
    - terraform
    - vscode
    - gcloud
    - kubectl
