- name: Spartan0nix dotfiles
  hosts: targetmachines
  vars:
    vscode_extensions:
      - redhat.ansible
      - redhat.vscode-yaml
      - akamud.vscode-theme-onedark
      - alexdima.copy-relative-path
      - golang.go
      - pkief.material-icon-theme
      - mhutchie.git-graph
      - jebbs.plantuml
      - hashicorp.terraform

  vars_prompt:
    - name: node_version
      prompt: Which version of node would you like to install ?
      default: "lts"

  pre_tasks:
    - name: Run pre tasks
      ansible.builtin.include_tasks: pre/main.yml
  post_tasks:
    - name: Run post tasks
      ansible.builtin.include_tasks: post/main.yml

  roles:
    - zsh
    - bottom
    - docker
    - gcloud
    - git
    - go
    - k9s
    - kubectl
    - neovim
    - vscode
    # --------------------
    # Installed with zsh
    # - python
    # - nerd_font
    # --------------------
    # Installed with neovim
    # - node
    # - terraform
    # --------------------

# For WSL
# when: ('WSL_DISTRO_NAME' in ansible_env)
