---
# when: lookup('env', 'WSL_DISTRO_NAME') == ""

- include: setup_debian.yml
  when: (CURRENT_DISTRO == "Debian") and (lookup('env', 'WSL_DISTRO_NAME') == "")

- name: Add vscode bin to PATH if running WSL
  shell: |
    echo "\nexport PATH=\$PATH:{{ WSL_VSCODE_PATH }}" >> {{ ansible_user_dir }}/.bashrc
    echo "\nexport PATH=\$PATH:{{ WSL_VSCODE_PATH }}" >> {{ ansible_user_dir }}/.zshrc
  when: WSL_VSCODE_PATH is defined

- name: Install extensions
  shell: |
    code --install-extension "{{ item }}"
  loop: "{{ vscode_extensions }}"
