- name: Install for Debian
  ansible.builtin.include_tasks: setup_debian.yml
  when: (CURRENT_DISTRO == "Debian") and ('WSL_DISTRO_NAME' not in ansible_env)

- name: Install server
  ansible.builtin.include_tasks: setup_server.yml
  when: ('WSL_DISTRO_NAME' in ansible_env)

- name: Configure WSL
  ansible.builtin.include_tasks: configure_wsl.yml
  when: ('WSL_DISTRO_NAME' in ansible_env) and (WSL_VSCODE_PATH is defined)

- name: Install extensions
  ansible.builtin.command: code --install-extension "{{ item }}"
  register: vscode_extension
  changed_when: vscode_extension.rc != 0
  loop: "{{ vscode_extensions }}"
