---
- name: Install for Debian
  ansible.builtin.include_tasks: setup_debian.yml
  when: (ansible_distribution == "Debian") and ('WSL_DISTRO_NAME' not in ansible_env)

- name: Install Vscode server only (for WSL)
  ansible.builtin.include_tasks: setup_server.yml
  when: ('WSL_DISTRO_NAME' in ansible_env)

- name: Add Windows host Vscode binairies to the path
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.path"
    regex: '^PATH=\$PATH:{{ WSL_VSCODE_PATH }}'
    line: "PATH=$PATH:{{ WSL_VSCODE_PATH }}"
  notify:
    - "Add Windows host Vscode binairies to the path (doc)"
  when: ('WSL_DISTRO_NAME' in ansible_env) and (WSL_VSCODE_PATH is defined)

- name: Install extensions
  ansible.builtin.command: code --install-extension "{{ item }}"
  register: vscode_extension
  changed_when: vscode_extension.rc != 0
  loop: "{{ vscode_extensions }}"
