- name: Check if APT repo exist
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/vscode.list
  register: vscode_install
  become: true

- name: Install requirements
  ansible.builtin.package: # noqa package-latest
    name:
      - wget
      - gpg
    state: latest
  become: true
  when: not vscode_install.stat.exists

- name: Add APT repo
  ansible.builtin.shell: |
    set -o pipefail

    wget -qO- https://packages.microsoft.com/keys/microsoft.asc \
      | gpg --dearmor \
      | tee /etc/apt/trusted.gpg.d/packages.microsoft.gpg

    chmod 644 /etc/apt/trusted.gpg.d/packages.microsoft.gpg
    chown root:root /etc/apt/trusted.gpg.d/packages.microsoft.gpg

    echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" \
      | tee /etc/apt/sources.list.d/vscode.list
  become: true
  when: not vscode_install.stat.exists
  args:
    executable: /bin/bash

- name: Update package repositories
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: not vscode_install.stat.exists

- name: Install VScode binairies
  ansible.builtin.package: # noqa package-latest
    name:
      - code
    state: latest
  become: true
  when: not vscode_install.stat.exists
