- name: Check for previous vscode-server install
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.vscode-server"
  register: vscode_server_install

- name: Download install script
  ansible.builtin.get_url:
    url: https://aka.ms/install-vscode-server/setup.sh
    dest: /tmp/vscode-server-install.sh
    mode: 0744
  when: not vscode_server_install.stat.exists

- name: Execute install script
  ansible.builtin.command: /tmp/vscode-server-install.sh
  when: not vscode_server_install.stat.exists

- name: Remove install script
  ansible.builtin.file:
    path: /tmp/vscode-server-install.sh
    state: absent
  when: not vscode_server_install.stat.exists
