---
- name: Check if APT repo exist
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/vscode.list
  register: vscode_install
  become: true

- name: Install requirements
  ansible.builtin.package: # noqa package-latest
    name:
      - wget
      - gpg
    state: latest
  become: true
  when: not vscode_install.stat.exists

- name: Retrieve the APT repo key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /usr/share/keyrings/packages.microsoft.asc
    mode: "0444"
    owner: root
    group: root
  become: true
  when: not vscode_install.stat.exists

- name: Add the APT repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.asc] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode
  become: true
  when: not vscode_install.stat.exists

- name: Install VScode binairies
  ansible.builtin.package: # noqa package-latest
    name:
      - code
    state: latest
    update_cache: true
  become: true
  when: not vscode_install.stat.exists
