---
- name: Check for previous vscode-server install
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.vscode-server"
  register: vscode_server_install

- name: Download the install script
  ansible.builtin.get_url:
    url: https://aka.ms/install-vscode-server/setup.sh
    dest: /tmp/vscode-server-install.sh
    mode: "0500"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  when: not vscode_server_install.stat.exists

- name: Execute the install script
  ansible.builtin.command: /tmp/vscode-server-install.sh
  register: vscode_server_script
  changed_when: vscode_server_script.rc == 0
  when: not vscode_server_install.stat.exists

- name: Remove the install script
  ansible.builtin.file:
    path: /tmp/vscode-server-install.sh
    state: absent
  when: not vscode_server_install.stat.exists
