- name: Set bash completion (doc)
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: '^source \<\(kubectl completion bash\)'
    regexp: '^# Enable kubectl bash autocompletion'
    line: "\n# Enable kubectl bash autocompletion"

- name: Set zsh completion (doc)
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    insertbefore: '^source \<\(kubectl completion zsh\)'
    regexp: '^# Enable kubectl zsh autocompletion'
    line: "\n# Enable kubectl zsh autocompletion"
