---
- name: Install requirements
  ansible.builtin.package: # noqa package-latest
    name:
      - python3
      - python3-pip
    state: latest
  become: true

- name: Extract python version
  ansible.builtin.shell: |
    set -o pipefail
    python3 --version | sed -r 's/Python ([0-9]\.[0-9]+)\.[0-9]+/\1/'
  args:
    executable: /bin/bash
  register: python_version
  changed_when: python_version.rc == 0

- name: Remove python 'EXTERNALLY-MANAGED' flag
  ansible.builtin.file:
    path: "/usr/lib/python{{ python_version.stdout }}/EXTERNALLY-MANAGED"
    state: absent
  become: true

- name: Update pip3
  ansible.builtin.command: pip3 install --upgrade pip
  register: pip_upgrade
  changed_when: pip_upgrade.rc == 0
