---
- name: Install requirements
  package:
    name:
      - python3
      - python3-pip
    state: latest
  become: true

- name: Update pip3
  command: pip3 install --upgrade pip
  become: true