---
- name: Install requirements
  package:
    name:
      - curl
      - zsh
      - git
    state: latest
  become: true

- name: Set ZSH as default shell
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/zsh
  become: true

- name: Download Oh-my-zsh install script
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh

- name: Execute Oh-my-zsh install script
  shell: sh /tmp/ohmyzsh_install.sh
  become_user: "{{ ansible_env['USER'] }}"  

- name: Create NerdFont directory
  file:
    path: "{{ ansible_user_dir }}/.local/share/fonts"
    state: directory

- name: Install NerdFont 'Caskaydia Cove Regular'
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Regular%20Nerd%20Font%20Complete.otf"
    dest: "{{ ansible_user_dir }}/.local/share/fonts/Caskaydia-Cove-Regular-Nerd-Font-Complete.otf"

- name: Copy ZSH user configuration
  copy:
    dest: "{{ ansible_user_dir }}/.zshrc"
    src: .zshrc

- name: Install ZSH syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh//plugins/zsh-syntax-highlighting"

- name: Install ZSH autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/plugins/zsh-autosuggestions"

- name: Install ZSH history substring search
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/plugins/zsh-history-substring-search"

- name: Install ZSH completions
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/plugins/zsh-completions"

