---
- name: Install requirements
  package:
    name:
      - curl
      - zsh
      - git
      - zplug
    state: latest
  become: true

- name: Install python requirements
  pip: 
    name: pexpect
  become: true

- name: Create NerdFont directory
  file:
    path: "{{ ansible_user_dir }}/.local/share/fonts"
    state: directory

- name: Install NerdFont 'Caskaydia Cove Regular'
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Regular%20Nerd%20Font%20Complete.otf"
    dest: "{{ ansible_user_dir }}/.local/share/fonts/Caskaydia-Cove-Regular-Nerd-Font-Complete.otf"

- name: Copy ZSH user configuration
  copy:
    dest: "{{ ansible_user_dir }}/.zshrc"
    src: .zshrc
  