---
- name: Install requirements
  ansible.builtin.package: # noqa: package-latest
    name:
      - curl
      - zsh
      - git
    state: latest
  become: true

- name: Install pexpect
  ansible.builtin.pip:
    name: pexpect

- name: Set ZSH as default shell
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/zsh
  become: true

- name: Check previous Oh-my-zsh install
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: ohmyzsh_install

- name: Download Oh-my-zsh install script
  ansible.builtin.get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
    mode: "0550"
  when: not ohmyzsh_install.stat.exists

- name: Execute Oh-my-zsh install script
  ansible.builtin.shell: |
    set -o pipefail
    echo -e "Y" | bash /tmp/ohmyzsh_install.sh
  args:
    executable: /bin/bash
  become_user: "{{ ansible_env['USER'] }}"
  when: not ohmyzsh_install.stat.exists

- name: Remove Oh-my-zsh install script
  ansible.builtin.file:
    path: /tmp/ohmyzsh_install.sh
    state: absent
  when: not ohmyzsh_install.stat.exists

- name: Check previous ZSH configuration file
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: "# Custom script marker"
    state: present
  check_mode: true
  notify:
    - Copy ZSH user configuration
    - Install ZSH plugin - syntax highlighting
    - Install ZSH plugin - autosuggestions
    - Install ZSH plugin - substring search
    - Install ZSH plugin - completions
