---
- name: Include .path file in bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: "^source ~/.path"
    line: "source ~/.path"
  register: path_bashrc

- name: Include .path file in bashrc (doc)
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: "# Source file containing path update"
    line: "\n# Source file containing path update"
    insertbefore: "^source ~/.path"
  when: path_bashrc.changed

- name: Check if '.zshrc' exists
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.zshrc"
  register: zshrc_exist

- name: Include .path file in zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: '^source ~/.path'
    line: "source ~/.path"
  register: path_zshrc
  when: zshrc_exist.stat.exists

- name: Include .path file in zshrc (doc)
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: "# Source file containing path update"
    line: "\n# Source file containing path update"
    insertbefore: "^source ~/.path"
  when: path_zshrc.changed
