# ----------------------------------------------
- name: Include .path file in bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^source ~/.path'
    line: 'source ~/.path'
  register: bashrc_update

- name: Add documentation for .path import in bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: '^source ~/.path'
    line: "\n# Source file containing path update"
  when: bashrc_update.changed

- name: Add function cdw to bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    marker_begin: BEGIN CDW
    marker_end: END CDW
    block: |
      function cdw() {
          if [[ $# -ge 1 ]]; then
              converted_path=$(echo $1 | sed 's/C\:/c/' | sed 's/\\/\//g')
              cd_target="/mnt/${converted_path}"
              if [[ $2 == "--print" ]]; then
                echo $cd_target
              else
                cd $cd_target
              fi
          else
              echo "Missing required Windows path"
          fi
          unset converted_path
          unset cd_target
      }
  register: cdw_bashrc
  when: ('WSL_DISTRO_NAME' in ansible_env)

- name: Add space before cdw function in bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: "# BEGIN CDW ANSIBLE MANAGED BLOCK"
    line: "\n# Convert a Windows PATH to a linux PATH before executin 'cd'"
  when: cdw_bashrc.changed
# ----------------------------------------------

# ----------------------------------------------
- name: Include .path file in zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: '^source ~/.path'
    line: 'source ~/.path'
    create: true
  register: zshrc_update

- name: Add documentation for .path import in zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    insertbefore: '^source ~/.path'
    line: "\n# Source file containing path update"
  when: zshrc_update.changed

- name: Add function cdw to zshrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    marker_begin: BEGIN CDW
    marker_end: END CDW
    block: |
      function cdw() {
          if [ $# -ge 1 ]; then
              converted_path=$(print -P '%{$1%}' | sed 's/C\:/c/' | sed 's/\\/\//g')
              cd_target="/mnt/${converted_path}"
              if [ "$2" = "--print" ]; then
                echo $cd_target
              else
                cd $cd_target
              fi
          else
              echo "Missing required Windows path"
          fi
          unset converted_path
          unset cd_target
      }
  register: zsh_bashrc
  when: ('WSL_DISTRO_NAME' in ansible_env)

- name: Add space before cdw function in zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    insertbefore: "# BEGIN CDW ANSIBLE MANAGED BLOCK"
    line: "\n# Convert a Windows PATH to a linux PATH before executin 'cd'"
  when: zsh_bashrc.changed
# ----------------------------------------------
