- name: Install for Debian
  ansible.builtin.include_tasks: setup_debian.yml
  when: ansible_distribution == "Debian"

- name: Set bash completion
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^source \<\(kubectl completion bash\)'
    line: "source <(kubectl completion bash)"
  notify:
    - "Set bash completion (doc)"

- name: Check if '.zshrc' exist
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.zshrc"
  register: zshrc_file

- name: Set zsh completion
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: '^source \<\(kubectl completion zsh\)'
    line: "source <(kubectl completion zsh)"
  notify:
    - "Set zsh completion (doc)"
  when: zshrc_file.stat.exists
