- name: Install for Debian
  ansible.builtin.include_tasks: setup_debian.yml
  when: CURRENT_DISTRO == "Debian"

- name: Set bash completion
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: 'source <(kubectl completion bash)'
    regexp: '^source <\(kubectl completion bash\)'
  notify:
    - Add documentation for bash completion

- name: Set zsh completion
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: 'source <(kubectl completion zsh)'
    regexp: '^source <\(kubectl completion zsh\)'
  notify:
    - Add documentation for zsh completion
