---
- include_tasks: setup_debian.yml
  when: CURRENT_DISTRO == "Debian"

- name: Set bash completion
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: 'source <(kubectl completion bash)'
    regexp: '^source <\(kubectl completion bash\)'
  register: bash_completion

- name: Add documentation for bash completion
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: '^source <\(kubectl completion bash\)'
    line: "\n# Enable kubectl bash autocompletion"
  when: bash_completion.changed

- name: Set zsh completion
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: 'source <(kubectl completion zsh)'
    regexp: '^source <\(kubectl completion zsh\)'
  register: zsh_completion

- name: Add documentation for zsh completion
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    insertbefore: '^source <\(kubectl completion zsh\)'
    line: "\n# Enable kubectl zsh autocompletion"
  when: zsh_completion.changed