---
- name: Check if APT repo exist
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/kubernetes.list
  register: kubectl_install
  become: true

- name: Install requirements
  ansible.builtin.apt: # noqa package-latest
    name:
      - wget
      - gpg
    state: latest
  become: true
  when: not kubectl_install.stat.exists

- name: Retrieve the APT repo key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.asc
    mode: "0444"
    owner: root
    group: root
  become: true
  when: not kubectl_install.stat.exists

- name: Add the APT repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.asc] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes
  become: true
  when: not kubectl_install.stat.exists

- name: Install kubectl
  ansible.builtin.package: # noqa package-latest
    name:
      - kubectl
    state: latest
    update_cache: true
  become: true
  when: not kubectl_install.stat.exists
