- name: Check if APT repo exist
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/kubernetes.list
  register: kubectl_install
  become: true

- name: Install requirements
  ansible.builtin.package: # noqa package-latest
    name:
      - wget
      - gpg
    state: latest
  become: true
  when: not kubectl_install.stat.exists

- name: Add APT repo
  ansible.builtin.shell: |
    set -o pipefail

    wget -qO- https://packages.cloud.google.com/apt/doc/apt-key.gpg \
      | gpg --dearmor \
      | tee /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg

    chmod 644 /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
    chown root:root /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg

    echo "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" \
      | tee /etc/apt/sources.list.d/kubernetes.list
  become: true
  when: not kubectl_install.stat.exists
  args:
    executable: /bin/bash

- name: Update package repositories
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: not kubectl_install.stat.exists

- name: Install kubectl
  ansible.builtin.package: # noqa package-latest
    name:
      - kubectl
    state: latest
  become: true
  when: not kubectl_install.stat.exists
