- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a testing network
      community.docker.docker_network:
        name: dotfiles_molecule
        ipam_config:
          - subnet: 172.150.0.0/24

    - name: Create a container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        entrypoint: []
        user: root
        command: sleep 1d
        log_driver: json-file
        networks:
          - name: dotfiles_molecule
      loop: "{{ molecule_yml.platforms }}"
