---
- name: Deploy a hello-world container
  community.docker.docker_container:
    name: hello-world
    image: hello-world
    state: started
    cleanup: true
  register: container_output

- name: Validate the deployment
  ansible.builtin.assert:
    that:
      - container_output is not failed
      - container_output.container.RestartCount == 0
      - container_output.container.State.ExitCode == 0
      - container_output.container.State.Paused == false
      - container_output.container.State.Restarting == false
      - container_output.container.State.Status == "exited"

- name: Remove the hello-world image
  community.docker.docker_image_remove:
    name: hello-world
    tag: latest
