---
- name: Install packages
  ansible.builtin.package: # noqa : package-latest
    name:
      - git
    state: latest
  become: true

- name: Config user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  no_log: true

- name: Config user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"
  no_log: true

- name: Config pull.rebase
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: false

- name: Create user ssh folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0754"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Check if a ssh keys pair already exist
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.ssh/id_git"
  register: ssh_keys

- name: Generate ssh key
  community.crypto.openssh_keypair:
    path: "{{ ansible_user_dir }}/.ssh/id_git"
    type: ed25519
    # comment: "{{ git_email }}"
  when: not ssh_keys.stat.exists

- name: Check if ssh config file exist
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.ssh/config"
  register: ssh_config

- name: Create ssh config file
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh/config"
    state: touch
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  when: not ssh_config.stat.exists

- name: Add default ssh config (example, github, gitlab)
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.ssh/config"
    block: |
      # Host example.com
          # PreferredAuthentications publickey
          # IdentityFile ~/.ssh/id_rsa

      Host github.com
          PreferredAuthentications publickey
          IdentityFile ~/.ssh/id_git

      Host gitlab.com
          PreferredAuthentications publickey
          IdentityFile ~/.ssh/id_git
  when: not ssh_config.stat.exists
