---
- name: Install packages
  package:
    name:
      - git
    state: latest
  become: true

- name: Config user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  no_log: true

- name: Config user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"
  no_log: true

- name: Create user ssh folder
  file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory

- name: Check if a ssh keys pair already exist
  stat:
    path: "{{ ansible_user_dir }}/.ssh/id_git"
  register: ssh_keys

- name: Generate ssh key
  community.crypto.openssh_keypair:
    path: "{{ ansible_user_dir }}/.ssh/id_git"
    type: ed25519
    comment: "{{ git_email }}"
  when: not ssh_keys.stat.exists

- name: Set fact SSH_KEY_NOT_CHANGED
  set_fact:
    SSH_KEY_NOT_CHANGED: true
  when: ssh_keys.stat.exists

- name: Create ssh config file
  file:
    path: "{{ ansible_user_dir }}/.ssh/config"
    state: touch

- name: Add default ssh config (example, github, gitlab)
  blockinfile:
    path: "{{ ansible_user_dir }}/.ssh/config"
    block: |
      # Host example.com
          # PreferredAuthentications publickey
          # IdentityFile ~/.ssh/id_rsa

      Host github.com
          PreferredAuthentications publickey
          IdentityFile ~/.ssh/id_git

      Host gitlab.com
          PreferredAuthentications publickey
          IdentityFile ~/.ssh/id_git