- name: Add NODE_EXTRA_CA_CERTS documentation
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.path"
    insertbefore: '^NODE_EXTRA_CA_CERTS={{ ca_file }}'
    line: "\n# Add nodejs custom CA environment variable"
