driver:
  name: docker

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

platforms:
  - name: debian-bookworm
    image: debian:bookworm
    package_manager: apt
    context: docker
  - name: debian-bookworm-wsl
    image: debian:bookworm
    package_manager: apt
    context: wsl
  - name: debian-bullseye
    image: debian:bullseye
    package_manager: apt
    context: docker
  - name: debian-bullseye-wsl
    image: debian:bullseye
    package_manager: apt
    context: wsl

provisioner:
  name: ansible
  inventory:
    hosts:
      molecule:
        hosts:
          debian-bookworm:
          debian-bookworm-wsl:
          debian-bullseye:
          debian-bullseye-wsl:
        vars:
          ansible_connection: community.docker.docker
          ansible_become_method: su
          docker_disable_tests: true


scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - destroy
          