---
- name: Install requirements
  package:
    name:
      - curl
    state: latest
  become: true

- name: Get deb package URL
  github_release:
    repo_name: bottom
    repo_owner: ClementTsang
    asset_name: amd64.deb
  register: bottom_dl_url
  
- name: Download deb package
  get_url:
    url: "{{ bottom_dl_url.url }}"
    dest: /tmp/bottom_amd64.deb
  
- name: Install deb package
  shell: |
    dpkg -i /tmp/bottom_amd64.deb
  become: true

- name: Remove deb package
  file:
    path: /tmp/bottom_amd64.deb
    state: absent
