- name: Check previous bottom install
  ansible.builtin.shell: |
    dpkg-query -W --showformat='${Version}\n' bottom
  ignore_errors: true
  register: bottom_install
  changed_when: bottom_install.rc == 1

- name: Get deb package URL
  github_release:
    repo_name: bottom
    repo_owner: ClementTsang
    asset_name: amd64.deb
  register: bottom_dl_url
  when: bottom_install.rc == 1

- name: Download deb package
  ansible.builtin.get_url:
    url: "{{ bottom_dl_url.url }}"
    dest: /tmp/bottom_amd64.deb
    mode: "0750"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  when: bottom_install.rc == 1

- name: Install deb package
  ansible.builtin.apt:
    deb: /tmp/bottom_amd64.deb
  become: true
  when: bottom_install.rc == 1

- name: Remove deb package
  ansible.builtin.file:
    path: /tmp/bottom_amd64.deb
    state: absent
  when: bottom_install.rc == 1
