---
- name: Check previous bottom install
  shell: |
    dpkg-query -W --showformat='${Version}\n' bottom
  ignore_errors: true
  register: bottom_install

- name: Get deb package URL
  github_release:
    repo_name: bottom
    repo_owner: ClementTsang
    asset_name: amd64.deb
  register: bottom_dl_url
  when: bottom_install.rc != 0

- name: Download source
  get_url:
    url: "{{ bottom_dl_url.url }}"
    dest: /tmp/bottom_amd64.deb
  when: bottom_install.rc != 0
  
- name: Install deb package
  apt:
    deb: /tmp/bottom_amd64.deb
  become: true
  when: bottom_install.rc != 0

- name: Remove source
  file:
    path: /tmp/bottom_amd64.deb
    state: absent
  when: bottom_install.rc != 0
