- name: Delete
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete the container
      community.docker.docker_container:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ molecule_yml.platforms }}"

    - name: Delete the network
      community.docker.docker_network:
        name: dotfiles_molecule
        state: absent
