- name: Install requirements
  ansible.builtin.package: # noqa : package-latest
    name:
      - git
    state: latest
  become: true

- name: Checking for previous Go install
  ansible.builtin.stat:
    path: /usr/local/go
  register: go_install

- name: Get latest tag
  ansible.builtin.shell: |
    set -o pipefail
    git ls-remote --tags https://github.com/golang/go.git | grep -E '\bgo1\b\.[0-9]{2,}\.[0-9]{1,2}' | cut --delimiter="/" --fields=3 | sort -n | tail -1
  args:
    executable: /bin/bash
  register: go_tag
  when: not go_install.stat.exists

- name: Unarchive Go binairies
  ansible.builtin.unarchive:
    src: "https://go.dev/dl/{{ go_tag.stdout }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: true
  when: not go_install.stat.exists
  become: true

- name: Add Go path
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.path"
    regexp: '^PATH=\$PATH:/usr/local/go/bin:\$HOME/go/bin'
    line: 'PATH=$PATH:/usr/local/go/bin:$HOME/go/bin'
  when: not go_install.stat.exists

- name: Add Go path documentation
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.path"
    insertbefore: '^PATH=\$PATH:/usr/local/go/bin:\$HOME/go/bin'
    line: "\n# Add Go binairies to PATH"
  when: not go_install.stat.exists

- name: Install Gopls
  ansible.builtin.shell: |
    export PATH=\$PATH:/usr/local/go/bin:\$HOME/go/bin
    go install golang.org/x/tools/gopls@latest
  when: not go_install.stat.exists
