---
- name: Install requirements
  package:
    name:
      - git
    state: latest
  become: true

- name: Checking for previous Go install
  stat:
    path: /usr/local/go
  register: go_install

- name: Get latest tag
  shell: |
    git ls-remote --tags https://github.com/golang/go.git | grep -E '\bgo1\b\.[0-9]{2,}\.[0-9]{1,2}' | cut --delimiter="/" --fields=3 | sort -n | tail -1
  register: go_tag
  when: not go_install.stat.exists

- name: Unarchive Go binairies
  unarchive:
    src: "https://go.dev/dl/{{ go_tag.stdout }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: true
  when: not go_install.stat.exists
  become: true

- name: Sef fact GO_PATH
  set_fact: 
    GO_PATH: "/usr/local/go/bin:\\$HOME/go/bin"
  when: not go_install.stat.exists

- name: Install Gopls
  shell: |
    export PATH=\$PATH:"{{ GO_PATH }}"
    go install golang.org/x/tools/gopls@latest
  when: not go_install.stat.exists