---
- name: Install requirements
  ansible.builtin.package: # noqa : package-latest
    name:
      - git
    state: latest
  become: true

- name: Check for previous Go install
  ansible.builtin.stat:
    path: /usr/local/go
  register: go_install

- name: Get latest tag
  ansible.builtin.shell: |
    set -o pipefail
    git ls-remote --tags https://github.com/golang/go.git | grep -E '\bgo1\b\.[0-9]{2,}\.[0-9]{1,2}' | cut --delimiter="/" --fields=3 | sort -n | tail -1
  args:
    executable: /bin/bash
  register: go_tag
  changed_when: go_tag.rc == 0
  when: not go_install.stat.exists

- name: Unarchive Go binairies
  ansible.builtin.unarchive:
    src: "https://go.dev/dl/{{ go_tag.stdout }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: true
  when: not go_install.stat.exists
  become: true

- name: Add Go binairies to the path
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.path"
    regexp: '^PATH=\$PATH:/usr/local/go/bin:\$HOME/go/bin'
    line: "PATH=$PATH:/usr/local/go/bin:$HOME/go/bin"
  notify:
    - "Add Go binairies to the path (doc)"
  when: not go_install.stat.exists

- name: Install gopls
  ansible.builtin.command: /usr/local/go/bin/go install golang.org/x/tools/gopls@latest
  register: gopls_install
  changed_when: gopls_install.rc == 0
  when: not go_install.stat.exists
