---
- name: Install requirements
  package:
    name:
      - wget
      - gpg
    state: latest
  become: true
  
- name: Add APT repository
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  become: true
  args:
    warn: false

- name: Update package repositories
  apt:
    update_cache: yes
  become: true

- name: Install package
  package:
    name:
      - terraform
    state: latest
  become: true