- name: Check if APT repo exist
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/hashicorp.list
  register: terraform_install
  become: true

- name: Install requirements
  ansible.builtin.package: # noqa package-latest
    name:
      - wget
      - gpg
    state: latest
  become: true
  when: not terraform_install.stat.exists

- name: Add APT repository
  ansible.builtin.shell: |
    set -o pipefail

    wget -O- https://apt.releases.hashicorp.com/gpg \
      | gpg --dearmor \
      | tee /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg

    chmod 644 /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg
    chown root:root /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg

    echo "deb [signed-by=/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
      | tee /etc/apt/sources.list.d/hashicorp.list
  become: true
  when: not terraform_install.stat.exists
  args:
    executable: /bin/bash

- name: Update package repositories
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: not terraform_install.stat.exists

- name: Install package
  ansible.builtin.package: # noqa package-latest
    name:
      - terraform
    state: latest
  become: true
  when: not terraform_install.stat.exists
