---
- name: Check if APT repo exist
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/hashicorp.list
  register: terraform_install
  become: true

- name: Install requirements
  ansible.builtin.package: # noqa package-latest
    name:
      - wget
      - gpg
    state: latest
  become: true
  when: not terraform_install.stat.exists

- name: Retrieve the APT repo key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    mode: "0444"
    owner: root
    group: root
  become: true
  when: not terraform_install.stat.exists

- name: Add the APT repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp
  become: true
  when: not terraform_install.stat.exists

- name: Install package
  ansible.builtin.package: # noqa package-latest
    name:
      - terraform
    state: latest
    update_cache: true
  become: true
  when: not terraform_install.stat.exists
