---
- name: Check if APT repo exist
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/google-cloud-sdk.list
  register: gcloud_install
  become: true

- name: Install requirements
  ansible.builtin.apt: # noqa package-latest
    name:
      - wget
      - gpg
    state: latest
  become: true
  when: not gcloud_install.stat.exists

- name: Retrieve the APT repo key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/cloud.google.asc
    mode: "0444"
    owner: root
    group: root
  become: true
  when: not gcloud_install.stat.exists

- name: Add the APT repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/cloud.google.asc] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    filename: google-cloud-sdk
  become: true
  when: not gcloud_install.stat.exists

- name: Install packages
  ansible.builtin.package: # noqa package-latest
    name:
      - google-cloud-cli
      - google-cloud-sdk-gke-gcloud-auth-plugin
    state: latest
    update_cache: true
  become: true
  when: not gcloud_install.stat.exists
