---
- name: Install packages
  package:
    name:
      - nodejs
      - npm
    state: latest
  become: true

- name: Retrieve npm config
  command: npm config list --json
  register: npm_config

- name: Setting ca_file fact
  set_fact: 
    ca_file: "{{ (npm_config.stdout|from_json).cafile }}"

- name: Setting custom CA certificate on global config
  command: npm config set --location=global cafile {{ ca_file }}
  when: ca_file != ""
  become: true

- name: Install npm package 'n'
  npm:
    name: n
    global: yes
  become: true

- name: Install latest node version
  shell: n latest
  become: true