- name: Install packages
  ansible.builtin.package: # noqa package-latest
    name:
      - nodejs
      - npm
    state: latest
  become: true

- name: Retrieve npm config
  ansible.builtin.command: npm config list --json
  register: npm_config
  changed_when: npm_config.rc != 0

- name: Set ca_file fact
  ansible.builtin.set_fact: # noqa yaml
    ca_file: "{{ (npm_config.stdout | from_json).cafile }}"

- name: Setup custom CA
  ansible.builtin.include_tasks: setup_ca.yml
  when: ca_file != ""

- name: Install npm package 'n'
  community.general.npm:
    name: n
    global: true
  become: true

- name: Install desired node version
  ansible.builtin.command: "n {{ node_version }}"
  register: node_install
  changed_when: node_install.rc != 0
  become: true
