---
- name: Install requirements
  package:
    name:
      - jq
    state: latest
  become: true

- name: Download install script
  get_url:
    url: https://deb.nodesource.com/setup_lts.x
    dest: /tmp/setup_lts.sh

- name: Execute install script
  command: bash /tmp/setup_lts.sh
  become: true

- name: Remove install script
  file:
    path: "/tmp/setup_lts.sh"
    state: absent
  become: true

- name: Install nodejs
  package:
    name:
      - nodejs
    state: latest
  become: true

- name: Retrieve npm config
  command: npm config list --json
  register: npm_config

- name: Setting ca_file fact
  set_fact: 
    ca_file: "{{ (npm_config.stdout|from_json).cafile }}"

- name: Setting custom CA certificate on global config
  command: npm config set --location=global cafile {{ ca_file }}
  when: ca_file != ""
  become: true