---
- name: Install packages
  package:
    name:
      - nodejs
      - npm
    state: latest
  become: true

- name: Retrieve npm config
  command: npm config list --json
  register: npm_config

- name: Setting ca_file fact
  set_fact: 
    ca_file: "{{ (npm_config.stdout|from_json).cafile }}"

- name: Setting custom CA certificate on global config
  command: npm config set --location=global cafile {{ ca_file }}
  when: ca_file != ""
  become: true

- name: Add NODE_EXTRA_CA_CERTS environment variable
  lineinfile:
    path: "{{ ansible_user_dir }}/.path"
    regexp: '^NODE_EXTRA_CA_CERTS={{ ca_file }}'
    line: 'NODE_EXTRA_CA_CERTS={{ ca_file }}'
  when: ca_file != ""
  register: node_extra_certs_path

- name: Add NODE_EXTRA_CA_CERTS documentation
  lineinfile:
    path: "{{ ansible_user_dir }}/.path"
    insertbefore: '^NODE_EXTRA_CA_CERTS={{ ca_file }}'
    line: "\n# Add nodejs environment variable"
  when: node_extra_certs_path.changed

- name: Install npm package 'n'
  npm:
    name: n
    global: yes
  become: true

- name: Install latest node version
  shell: n latest
  become: true