- name: Setting custom CA certificate on global config
  ansible.builtin.command: npm config set --location=global cafile {{ ca_file }}
  register: node_global_ca_flag
  changed_when: node_global_ca_flag.rc != 0
  become: true

- name: Add NODE_EXTRA_CA_CERTS environment variable
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.path"
    regexp: '^NODE_EXTRA_CA_CERTS={{ ca_file }}'
    line: 'NODE_EXTRA_CA_CERTS={{ ca_file }}'
  notify:
    - Add NODE_EXTRA_CA_CERTS documentation
