---
- name: Download deb package
  ansible.builtin.get_url:
    url: "https://github.com/derailed/k9s/releases/download/{{ k9s_latest_version }}/k9s_linux_amd64.deb"
    dest: /tmp/k9s_linux_amd64.deb
    mode: "0640"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Install deb package
  ansible.builtin.apt:
    deb: /tmp/k9s_linux_amd64.deb
  become: true

- name: Remove deb package
  ansible.builtin.file:
    path: /tmp/k9s_linux_amd64.deb
    state: absent
