---
- name: Retrieve the installation package
  ansible.builtin.get_url:
    url: "https://github.com/derailed/k9s/releases/download/{{ k9s_latest_version.stdout }}/k9s_linux_amd64.deb"
    dest: /tmp/k9s_linux_amd64.deb
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0640"

- name: Install the package
  ansible.builtin.apt:
    deb: /tmp/k9s_linux_amd64.deb
  become: true

- name: Remove the installation package
  ansible.builtin.file:
    path: /tmp/k9s_linux_amd64.deb
    state: absent
