---
- name: Build ansible library path
  shell: |
    CURRENT_PATH=$(pwd)
    echo "$CURRENT_PATH/library"
  register: ansible_library

- name: Set fact for ANSIBLE_LIBRARY
  set_fact:
    ANSIBLE_LIBRARY: "{{ ansible_library.stdout }}"

- name: Get current Distro
  shell: |
    distro=$(lsb_release -si)
    echo $distro
  register: current_distro

- name: Set fact for CURRENT_DISTRO
  set_fact:
    CURRENT_DISTRO: "{{ current_distro.stdout }}"

- include: setup_wsl.yml
  when: lookup('env', 'WSL_DISTRO_NAME') != ""
