galaxy_info:
  author: Spartan0nix
  description: "Zsh install for dotfiles"
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bullseye
dependencies:
  - role: python
  - role: nerd_font
