---
- name: Copy ZSH user configuration
  ansible.builtin.template:
    src: ".zshrc.j2"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0640"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Install ZSH plugin - syntax highlighting
  ansible.builtin.git: # noqa : latest
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh//plugins/zsh-syntax-highlighting"

- name: Install ZSH plugin - autosuggestions
  ansible.builtin.git: # noqa : latest
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/plugins/zsh-autosuggestions"

- name: Install ZSH plugin - substring search
  ansible.builtin.git: # noqa : latest
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/plugins/zsh-history-substring-search"

- name: Install ZSH plugin - completions
  ansible.builtin.git: # noqa : latest
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/plugins/zsh-completions"
