---
- name: Install packages
  package:
    name:
      - ca-certificates
      - curl
      - gnupg 
      - lsb-release
    state: latest
  become: true

- include_tasks: setup_debian.yml
  when: (CURRENT_DISTRO == "Debian")

- include_tasks: setup_wsl.yml
  when: lookup('env', 'WSL_DISTRO_NAME')