- name: Install packages
  ansible.builtin.package: # noqa package-latest
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
  become: true

- name: Install for Debian
  ansible.builtin.include_tasks: setup_debian.yml
  when: (CURRENT_DISTRO == "Debian")

- name: Configure for WSL
  ansible.builtin.include_tasks: setup_wsl.yml
  when: ('WSL_DISTRO_NAME' in ansible_env)
