---
- name: Add APT repo
  shell: |
    wget -qO- https://download.docker.com/linux/debian/gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/docker.gpg
    chmod 644 /etc/apt/trusted.gpg.d/docker.gpg
    chown root:root /etc/apt/trusted.gpg.d/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  become: true
  args:
    warn: false

- name: Update package repositories
  apt:
    update_cache: yes
  become: true

- name: Install docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
  become: true