---
- name: Check if APT repo exist
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_install
  become: true

- name: Retrieve the APT repo key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /usr/share/keyrings/docker.asc
    mode: "0444"
    owner: root
    group: root
  become: true
  when: not docker_install.stat.exists

- name: Add the APT repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true
  when: not docker_install.stat.exists

- name: Install docker packages
  ansible.builtin.apt: # noqa package-latest
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: true
  become: true
  when: not docker_install.stat.exists

- name: Add ansible user to docker group
  ansible.builtin.command: usermod -aG docker "{{ ansible_user_id }}"
  register: docker_group
  changed_when: docker_group.rc == 0
  become: true
  when: not docker_install.stat.exists
