---
- name: Setup service autostart (bash)
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    marker_begin: BEGIN DOCKER SERVICE
    marker_end: END DOCKER SERVICE
    block: |
      if service docker status 2>&1 | grep -q "is not running"; then
          /mnt/c/Windows/System32/wsl.exe -d "${WSL_DISTRO_NAME}" -u root -e /usr/sbin/service docker start >/dev/null 2>&1
      fi

- name: Setup service autostart (zsh)
  blockinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    marker_begin: BEGIN DOCKER SERVICE
    marker_end: END DOCKER SERVICE
    block: |
      if service docker status 2>&1 | grep -q "is not running"; then
          /mnt/c/Windows/System32/wsl.exe -d "${WSL_DISTRO_NAME}" -u root -e /usr/sbin/service docker start >/dev/null 2>&1
      fi