- name: Retrieve host PATH if running WSL
  ansible.builtin.shell: |
    IFS=:
    re=Microsoft\ VS\ Code\/bin
    for el in $PATH
    do
      if [[ "$el" =~ $re ]]
      then
        echo $el | sed 's/ /\\ /g'
      fi
    done
  args:
    executable: /bin/bash
  register: windows_host_path

- name: Set fact for VSCODE_PATH
  ansible.builtin.set_fact:
    WSL_VSCODE_PATH: "{{ windows_host_path.stdout }}"
