---
- name: Retrieve vscode binairies path from the PATH
  ansible.builtin.shell: |
    IFS=:
    re=Microsoft\ VS\ Code\/bin
    for entry in $PATH
    do
      if [[ "$entry" =~ $re ]]
      then
        echo $entry | sed 's/ /\\ /g'
      fi
    done
  args:
    executable: /bin/bash
  register: windows_host_path

- name: Set fact for VSCODE_PATH
  ansible.builtin.set_fact:
    WSL_VSCODE_PATH: "{{ windows_host_path.stdout }}"
