- name: Install default packages
  ansible.builtin.package:
    name:
      - git
      - jq
      - curl
      - net-tools
      - vim
      - bash-completion
      - wget
    state: latest
  become: true

- name: Extract vscode host path for WSL
  ansible.builtin.include_tasks: extract_vscode_path.yml
  when: ('WSL_DISTRO_NAME' in ansible_env)

- name: Create '.path' file
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.path"
    state: touch
    mode: "0750"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Update default PATH for WSL
  ansible.builtin.include_tasks: setup_wsl_path.yml
  when: ('WSL_DISTRO_NAME' in ansible_env)

