- name: Validate node prompt
  ansible.builtin.assert:
    that:
      - node_version is regex("(latest|lts|[0-9]+(\.[0-9]+)?(\.[0-9]+)?)")
    fail_msg: 'Node version should follow the given pattern "(latest|lts|[0-9]+(\.[0-9]+)?(\.[0-9]+)?)". Example : latest, lts, 18, 18.6, 18.6.0'

- name: Install default packages
  ansible.builtin.package:
    name:
      - git
      - jq
      - curl
      - net-tools
      - vim
    state: latest
  become: true

- name: Get Distro facts
  ansible.builtin.setup:
    gather_subset:
      - 'architecture'
      - 'distribution'
      - 'distribution_major_version'
      - 'distribution_release'
      - 'distribution_version'
  register: distro_facts

- name: Set CURRENT_DISTRO fact
  ansible.builtin.set_fact:
    CURRENT_DISTRO: "{{ distro_facts.ansible_facts.ansible_distribution }}"

# TODO - Update an switch to script block instead of custom module
# - include_tasks: extract_vscode_path.yml
#   when: ('WSL_DISTRO_NAME' in ansible_env)

- include_tasks: setup_path.yml
