---
- name: Install default packages
  package:
    name:
      - git
      - jq
      - curl
      - net-tools
    state: latest
  become: true

- name: Get Distro facts
  ansible.builtin.setup:
    gather_subset:
      - 'architecture'
      - 'distribution'
      - 'distribution_major_version'
      - 'distribution_release'
      - 'distribution_version'
  register: distro_facts

- name: Set CURRENT_DISTRO fact
  set_fact:
    CURRENT_DISTRO: "{{ distro_facts.ansible_facts.ansible_distribution }}"
  
- name: Set ANSIBLE_PLAYBOOK_ROOT fact
  set_fact:
    ANSIBLE_PLAYBOOK_ROOT: "{{ ansible_facts.env['PWD'] }}"

- include_tasks: setup_wsl.yml
  when: lookup('env', 'WSL_DISTRO_NAME') != ""

- name: Build ansible library path
  shell: |
    CURRENT_PATH=$(pwd)
    echo "$CURRENT_PATH/library"
  register: ansible_library

- name: Set ANSIBLE_LIBRARY fact
  set_fact:
    ANSIBLE_LIBRARY: "{{ ansible_library.stdout }}"

- include_tasks: setup_path.yml
