- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a testing network
      community.docker.docker_network:
        name: dotfiles_molecule
        ipam_config:
          - subnet: 172.150.0.0/24

    - name: Create a container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: sleep 1d
        log_driver: json-file
        networks:
          - name: dotfiles_molecule
        volumes:
          - '/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe:ro'
          - '/mnt/c/Users/leo/AppData/Local/Programs/Microsoft VS Code/bin/code.cmd:/mnt/c/Users/leo/AppData/Local/Programs/Microsoft VS Code/bin/code.cmd:ro'
      loop: "{{ molecule_yml.platforms }}"
