---
- name: Download install script
  get_url:
    url: https://aka.ms/install-vscode-server/setup.sh
    dest: /tmp/vscode-server-install.sh
  when: lookup('env', 'WSL_DISTRO_NAME') != ""

- name: Execute install script
  shell: sh /tmp/vscode-server-install.sh
  when: lookup('env', 'WSL_DISTRO_NAME') != ""

- name: Remove install script
  file:
    path: /tmp/vscode-server-install.sh
    state: absent
  when: lookup('env', 'WSL_DISTRO_NAME') != ""