---
- name: Download deb package
  ansible.builtin.get_url:
    url: "https://github.com/ClementTsang/bottom/releases/download/{{ bottom_latest_version }}/bottom_{{ bottom_latest_version }}_amd64.deb"
    dest: /tmp/bottom_latest_amd64.deb
    mode: "0640"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Install deb package
  ansible.builtin.apt:
    deb: /tmp/bottom_latest_amd64.deb
  become: true

- name: Remove deb package
  ansible.builtin.file:
    path: /tmp/bottom_latest_amd64.deb
    state: absent
