- name: Install requirements
  ansible.builtin.package: # noqa package-latest
    name:
      - xclip
      - git
    state: latest
  become: true

- name: Install for Debian
  ansible.builtin.include_tasks: setup_debian.yml
  when: CURRENT_DISTRO == "Debian"

- name: Checking for previous config
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/nvim"
  register: nvim_config

- name: Setup config
  ansible.builtin.include_tasks: setup_config.yml
  when: not nvim_config.stat.exists
