---
- name: Get download URL
  github_release:
    repo_name: neovim
    repo_owner: neovim
    asset_name: nvim-linux64.deb
  register: neovim_release

- name: Check previous neovim install
  shell: |
    dpkg-query -W --showformat='${Version}\n' neovim
  ignore_errors: true
  register: neovim_install

- name: Download deb package
  get_url: 
    url: "{{ neovim_release.url }}"
    dest: /tmp/nvim-linux64.deb
  when: neovim_install.rc != 0

- name: Install deb package
  apt:
    deb: /tmp/nvim-linux64.deb
  become: true
  when: neovim_install.rc != 0

- name: Remove deb package
  file:
    path: /tmp/nvim-linux64.deb
    state: absent
  become: true
  when: neovim_install.rc != 0