---
- name: Get download URL
  github_release:
    repo_name: neovim
    repo_owner: neovim
    asset_name: nvim-linux64.deb
  register: neovim_release

- name: Check previous neovim install
  script: "{{ ANSIBLE_PLAYBOOK_ROOT }}/scripts/check_version.py neovim {{ neovim_release.version }}"
  args:
    executable: python3
  register: bottom_install

- name: Download deb package
  get_url: 
    url: "{{ neovim_release.url }}"
    dest: /tmp/nvim-linux64.deb
  when: bottom_install.stdout != "match"

- name: Install deb package
  apt:
    deb: /tmp/nvim-linux64.deb
  become: true
  when: bottom_install.stdout != "match"

- name: Remove deb package
  file:
    path: /tmp/nvim-linux64.deb
    state: absent
  become: true
  when: bottom_install.stdout != "match"